import type { AiReadinessConfig, RobotsTxtConfig } from '../config.js'
import { writeOutput } from './write-output.js'

type RobotsRule = NonNullable<RobotsTxtConfig['rules']>[number]
type ContentSignals = NonNullable<RobotsTxtConfig['contentSignals']>

const TRAINING_BOT_RULES: RobotsRule[] = [
  { userAgent: 'GPTBot', disallow: ['/'], comment: 'OpenAI training crawler' },
  { userAgent: 'Google-Extended', disallow: ['/'], comment: 'Google Gemini training/grounding control token' },
  { userAgent: 'CCBot', disallow: ['/'], comment: 'Common Crawl' },
  { userAgent: 'ClaudeBot', disallow: ['/'], comment: 'Anthropic crawler' },
  { userAgent: 'anthropic-ai', disallow: ['/'], comment: 'Anthropic crawler' },
  { userAgent: 'Applebot-Extended', disallow: ['/'], comment: 'Apple AI training control token' },
]

const SEARCH_BOT_RULES: RobotsRule[] = [
  { userAgent: '*', allow: ['/'], comment: 'Default web and search discovery' },
  { userAgent: 'OAI-SearchBot', allow: ['/'], comment: 'OpenAI search crawler' },
]

function defaultSitemap(site: string): string {
  return new URL('sitemap-index.xml', site.endsWith('/') ? site : `${site}/`).toString()
}

function policyRules(policy: NonNullable<RobotsTxtConfig['policy']>): RobotsRule[] {
  if (policy === 'private') {
    return [{ userAgent: '*', disallow: ['/'], comment: 'Private site' }]
  }
  if (policy === 'training-opt-out') {
    return [...SEARCH_BOT_RULES, ...TRAINING_BOT_RULES]
  }
  return SEARCH_BOT_RULES
}

function defaultContentSignals(
  policy: NonNullable<RobotsTxtConfig['policy']>
): ContentSignals {
  if (policy === 'private') {
    return { search: 'no', aiTrain: 'no', aiInput: 'no' }
  }
  if (policy === 'training-opt-out') {
    return { search: 'yes', aiTrain: 'no', aiInput: 'yes' }
  }
  return { search: 'yes', aiTrain: 'yes', aiInput: 'yes' }
}

function composeRule(rule: RobotsRule): string[] {
  const lines: string[] = []
  const userAgents = Array.isArray(rule.userAgent) ? rule.userAgent : [rule.userAgent]

  if (rule.comment) lines.push(`# ${rule.comment}`)
  for (const userAgent of userAgents) {
    lines.push(`User-agent: ${userAgent}`)
  }
  for (const value of rule.allow ?? []) {
    lines.push(`Allow: ${value}`)
  }
  for (const value of rule.disallow ?? []) {
    lines.push(`Disallow: ${value}`)
  }
  if (rule.crawlDelay) {
    lines.push(`Crawl-delay: ${rule.crawlDelay}`)
  }
  return lines
}

/**
 * Returns the `Content-Signal` line, or `undefined` when every signal is
 * omitted. Callers must not emit the line in that case — a header with no
 * signals (`Content-Signal: `) is malformed, and a site that says nothing should
 * ship nothing rather than an empty directive.
 */
function composeContentSignal(signals: ContentSignals): string | undefined {
  const parts: string[] = []
  if (signals.search && signals.search !== 'omit') parts.push(`search=${signals.search}`)
  if (signals.aiTrain && signals.aiTrain !== 'omit') parts.push(`ai-train=${signals.aiTrain}`)
  if (signals.aiInput && signals.aiInput !== 'omit') parts.push(`ai-input=${signals.aiInput}`)
  if (parts.length === 0) return undefined
  return `Content-Signal: ${parts.join(', ')}`
}

/**
 * Pure composer for robots.txt.
 *
 * Presets are intentionally conservative: `training-opt-out` keeps ordinary
 * search discovery open and opts out of common model-training tokens. Some
 * vendors bundle training and grounding under one token, so consumers can
 * override the rules when answer-engine inclusion matters more than opt-out.
 */
export function composeRobotsTxt(
  config: AiReadinessConfig & { robotsTxt: RobotsTxtConfig }
): string {
  const robotsTxt = config.robotsTxt
  const policy = robotsTxt.policy ?? 'training-opt-out'
  const rules = robotsTxt.rules ?? policyRules(policy)
  const signals = {
    ...defaultContentSignals(policy),
    ...robotsTxt.contentSignals,
  }
  const sitemap = robotsTxt.sitemap === false ||
    (policy === 'private' && robotsTxt.sitemap === undefined)
    ? undefined
    : robotsTxt.sitemap ?? defaultSitemap(config.site)

  const contentSignal = composeContentSignal(signals)
  const lines: string[] = [
    '# Generated by @adkinn/astro-ai-readiness',
    ...(contentSignal ? [contentSignal] : []),
    '',
  ]

  for (const rule of rules) {
    lines.push(...composeRule(rule))
    lines.push('')
  }

  if (robotsTxt.additionalLines && robotsTxt.additionalLines.length > 0) {
    lines.push(...robotsTxt.additionalLines)
    lines.push('')
  }

  if (sitemap) {
    lines.push(`Sitemap: ${sitemap}`)
    lines.push('')
  }

  return lines.join('\n').replace(/\n+$/, '\n')
}

export async function writeRobotsTxt(
  config: AiReadinessConfig,
  dir: URL,
  logger: { info: (msg: string) => void; warn: (msg: string) => void }
): Promise<void> {
  if (!config.robotsTxt) return
  const content = composeRobotsTxt(
    config as AiReadinessConfig & { robotsTxt: RobotsTxtConfig }
  )
  const target = new URL('robots.txt', dir)
  await writeOutput(target, content, 'robots.txt', logger)
}
